// frontends/web-panel/src/app/core/theme/theme-toggle.component.ts
import { ChangeDetectionStrategy, Component, inject, Input } from '@angular/core';
import { ThemeService } from './theme.service';

/**
 * RutCampusTrack — Theme Toggle (Angular)
 *
 * Pill button that switches between dark and light themes. Uses Transit Grid
 * CSS variables for all colors so it auto-theme-matches. Accessible via
 * role="switch" and aria-checked.
 */
@Component({
  selector: 'app-theme-toggle',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button
      type="button"
      role="switch"
      [attr.aria-checked]="themeService.isDark()"
      [attr.aria-label]="themeService.isDark() ? 'Включить светлую тему' : 'Включить тёмную тему'"
      [title]="themeService.isDark() ? 'Светлая тема' : 'Тёмная тема'"
      [class.compact]="compact"
      class="theme-toggle"
      (click)="themeService.toggle()"
    >
      @if (themeService.isDark()) {
        <!-- Moon -->
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"
             stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
        </svg>
      } @else {
        <!-- Sun -->
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"
             stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <circle cx="12" cy="12" r="4" />
          <path d="M12 2v2" />
          <path d="M12 20v2" />
          <path d="m4.93 4.93 1.41 1.41" />
          <path d="m17.66 17.66 1.41 1.41" />
          <path d="M2 12h2" />
          <path d="M20 12h2" />
          <path d="m6.34 17.66-1.41 1.41" />
          <path d="m19.07 4.93-1.41 1.41" />
        </svg>
      }
    </button>
  `,
  styles: [
    `
      .theme-toggle {
        width: 40px;
        height: 40px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        border-radius: var(--radius-full);
        background: var(--bg-secondary);
        border: 1px solid var(--border-subtle);
        color: var(--text-primary);
        cursor: pointer;
        padding: 0;
        transition:
          background-color var(--duration-base) var(--ease-out),
          border-color var(--duration-base) var(--ease-out),
          transform var(--duration-fast) var(--ease-out),
          box-shadow var(--duration-base) var(--ease-out);
      }
      .theme-toggle.compact {
        width: 32px;
        height: 32px;
      }
      .theme-toggle svg {
        width: 20px;
        height: 20px;
      }
      .theme-toggle.compact svg {
        width: 16px;
        height: 16px;
      }
      .theme-toggle:hover {
        border-color: var(--border-accent);
        box-shadow: var(--glow-primary);
      }
      .theme-toggle:active {
        transform: scale(0.94);
      }
      .theme-toggle:focus-visible {
        outline: 2px solid var(--accent-primary);
        outline-offset: 2px;
      }
    `,
  ],
})
export class ThemeToggleComponent {
  themeService = inject(ThemeService);
  @Input() compact = false;
}

// frontends/pwa/src/shared/theme/ThemeToggle.tsx
import { useTheme } from './ThemeProvider'

/**
 * RutCampusTrack — Theme Toggle button
 *
 * Pill-shaped toggle with sun/moon icons. Uses Transit Grid tokens for all
 * colors so it looks correct in both themes automatically. Accessible:
 * exposes an aria-label + pressed state for the current theme.
 *
 * Place in headers, settings, or any visible chrome surface.
 */

interface ThemeToggleProps {
  /** Optional className for layout positioning. */
  className?: string
  /** Compact variant — smaller size for dense headers. */
  compact?: boolean
}

export function ThemeToggle({ className, compact = false }: ThemeToggleProps) {
  const { theme, toggleTheme } = useTheme()
  const isDark = theme === 'dark'
  const size = compact ? 32 : 40
  const iconSize = compact ? 16 : 20

  return (
    <button
      type="button"
      onClick={toggleTheme}
      role="switch"
      aria-checked={isDark}
      aria-label={isDark ? 'Включить светлую тему' : 'Включить тёмную тему'}
      title={isDark ? 'Светлая тема' : 'Тёмная тема'}
      className={className}
      style={{
        width: size,
        height: size,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 'var(--radius-full)',
        background: 'var(--bg-secondary)',
        border: '1px solid var(--border-subtle)',
        color: 'var(--text-primary)',
        cursor: 'pointer',
        transition:
          'background-color var(--duration-base) var(--ease-out), border-color var(--duration-base) var(--ease-out), transform var(--duration-fast) var(--ease-out), box-shadow var(--duration-base) var(--ease-out)',
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.borderColor = 'var(--border-accent)'
        e.currentTarget.style.boxShadow = 'var(--glow-primary)'
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.borderColor = 'var(--border-subtle)'
        e.currentTarget.style.boxShadow = 'none'
      }}
      onMouseDown={(e) => {
        e.currentTarget.style.transform = 'scale(0.94)'
      }}
      onMouseUp={(e) => {
        e.currentTarget.style.transform = 'scale(1)'
      }}
    >
      {isDark ? <MoonIcon size={iconSize} /> : <SunIcon size={iconSize} />}
    </button>
  )
}

function SunIcon({ size }: { size: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}

function MoonIcon({ size }: { size: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
    </svg>
  )
}
